function plotautoc(self);
%plotautoc: It plot the graph with all the cross-correlations generated by
%tscorr.
%See tscorr. for more details
%GM 2003

  
  [T,N] = size(self);
     ya = -( sum(self(:,1)<0)~=0 )
     nl = T/N;    
      B = zeros(nl,N*N);
     xx = (0:size(B(:,1),1)-1) ;
      x = (0:nl-1);
  figure
  for ii = 1:N;
    for jj = 1:N;
      for kk = 1:nl;
        B(kk,(ii-1)*N+jj) = self((kk-1)*N+ii,jj);
      end

      subplot(N,N,(ii-1)*N+jj)
      plot(xx,B(:,(ii-1)*N+jj),'LineWidth',2);
      tmp = ['acf(','var',num2str(ii),',var',num2str(jj),')'];
      title(tmp)
      axis([0 nl-1 ya 1])
      xlabel('lags')
    end
  end



